name: Skript
on:
  push:
    branches: [ feature/folia ]
    paths:
      - '.github/workflows/main.yml'
  schedule:
    - cron: '0 */5 * * *'
jobs:
  Skript:
    uses: HSGamer/ConstructProjects/.github/workflows/gradle-build.yml@main
    with:
      repository: "SkriptLang/Skript"
      target: "bin/*"
      name: "Skript"
      java: 21
      readonly: true
