name: zPlugins

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/zPlugins.yml'
  schedule:
    - cron: '0 */12 * * *'

jobs:
  zEssentials:
    uses: HSGamer/ConstructProjects/.github/workflows/gradle-build.yml@main
    with:
      repository: "Maxlego08/zEssentials"
      name: "zEssentials"
      java: 17
      target: "target/*"
      readonly: true

  zEssentials_discord_webhook:
    needs: zEssentials
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: HuskClaims
          path: ./artifact
      - name: List files
        run: ls -R ./artifact
      - name: Get artifact name
        id: get_artifact
        run: |
          FILE_NAME=$(ls ./artifact | head -n 1)
          echo "file_name=$FILE_NAME" >> $GITHUB_OUTPUT
        shell: bash
      - name: Send to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK2 }}
        run: |
          if [ -z "${{ steps.get_artifact.outputs.file_name }}" ]; then
            echo "No artifact found. Sending error message to Discord."
            curl -H "Content-Type: application/json" \
                 -d '{"content":"Error: No artifact was created in the HuskClaims build."}' \
                 $DISCORD_WEBHOOK
          else
            echo "Sending artifact to Discord: ${{ steps.get_artifact.outputs.file_name }}"
            curl -H "Content-Type: multipart/form-data" \
                 -F "file=@./artifact/${{ steps.get_artifact.outputs.file_name }}" \
                 -F "content=# Zessentials! #" \
                 $DISCORD_WEBHOOK
          fi
        shell: bash
